kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
    name: nginx-app-http
spec:
    hosts:
        - myhost.com
    scaleTargetRef:
        deployment: nginx-app
        service: nginx-app
        port: 80
    replicas:
        min: 1
        max: 10
    scaledownPeriod: 15
    scalingMetric: # requestRate and concurrency are mutually exclusive
        requestRate:
            granularity: 10s
            targetValue: 5
            window: 10s

